name: zipcode_jp
description: A starting point for Dart libraries or applications.
# version: 0.1.0
# homepage: https://www.example.com
# author: Hiroki Kaneko <kaneko.hiroki@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  csv: ^4.0.3
  archive: ^2.0.10

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
